### ISSUE TITLE
Selecting a maker in the search bar instead directs to their topmost sculpt result

### ISSUE THREAD

**Issue by rjboone** [keycap-archivist/website#381]
**Describe the bug**
When searching for a maker in the search bar, selecting their name under the "Artists" section instead directs to whichever sculpt is at the top of the "Sculpts" section. For example, searching for and selecting PrimeCaps directs to the page for TRDL V1 instead of their full sculpt catalogue. 

**To Reproduce**
1. Enter any maker name in the search bar
2. Click on their result under "Artists"
3. See error

**Expected behavior**
In the past, selecting a maker in the search bar has returned their full sculpt catalogue. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, Chrome
 - Version: 16.4, 112.0.5615.137 (respectively)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS 16.4.1 (a)
 - Browser: Safari
 - Version: 16.4.1

**Comment by zekth** [comment]
Oh interesting finding! I spotted a bug also with the result on a colorway. This happened when migrating to gatsby 5.

poke @theosenoussaoui for awareness

**Comment by zekth** [comment]
@rjboone i think that has been fixed. Could you confirm?

**Comment by rjboone** [comment]
> @rjboone i think that has been fixed. Could you confirm?

Looks like it! Will go ahead and close, thanks.
