### ISSUE TITLE
No tooltip on homepage star icons

### ISSUE THREAD

**Issue by hardiksharma11** [keycap-archivist/website#402]
**Bug**
The star icons on the homepage do not display tooltips. It is making confusion what this star is for.

**Steps to Reproduce**
1. Go to the homepage.
2. Hover over the star icons.
3. Notice that no tooltips are displayed.

**Expected behavior**
Tooltips to be displayed when hovering over the star icons on the homepage.

**Comment by zekth** [comment]
Would you like to send a PR to adress this issue?

**Comment by hardiksharma11** [comment]
Sure....
Can you tell what should be the text in the tooltip

**Comment by zekth** [comment]
`Add to wishlist` seems legit

**Comment by hardiksharma11** [comment]
OK. I am on it ...

**Comment by hardiksharma11** [comment]
#403 PR opened . . .
